- testdata/testdata.go
> Fix issue #13

- testdata/Makefile
Makefile to check Go sources
Fixes issue #11
> Makefile to check Go sources

- testdata/testdata.go
Extra data should be valid for tests purposes.
> Made Rule Extra data in JSON format

- docs/packages/testdata/testdata.html
Package documentation for testdata
> Package documentation for testdata

- reports/formatted/report_34c3ecc5-624a-49a5-bab8-4fdc5e51a266.json
- reports/formatted/report_74ae54aa-6577-4e80-85e7-697cb646ff37.json
- reports/formatted/report_a7467445-8d6a-43cc-b82c-7007664bdf69.json
- reports/formatted/report_ee7d2bf4-8933-4a3a-8634-3328fe806e08.json
- reports/formatted/report_eeeeeeee-eeee-eeee-eeee-000000000001.json
Formatted reports in JSON format
> Formatted reports in JSON format

- docs/packages/testdata/testdata.html
Added license to generated doc
> Added license to generated doc

- testdata/Makefile
Added target to generate doc into `Makefile`
> Added target to generate doc into Makefile

- docs/packages/testdata/testdata.html
Updated testdata documentation
N/A
> Updated testdata documentation

- docs/packages/testdata/testdata.html
Updated documentation again
N/A
> Updated documentation again

- testdata/testdata.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
> some fixes

- docs/packages/testdata/testdata.html
Updated documentation for testdata
N/A
> Updated documentation for testdata

- testdata/testdata.go
It's needed for this PR https://github.com/RedHatInsights/insights-results-smart-proxy/pull/211
> Added Report3SingleRuleExpectedResponse for single endpoint test in smart proxy

- messages/normal/tutorial_only.json
Fixed tutorial-only JSON file
Fixes issue #59 
N/A
> Fixed tutorial-only JSON file

- messages/normal/produce.sh
Script to produce messages to Kafka
Fixes #61
N/A
> Script to produce messages to Kafka

- go.mod
- go.sum
- testdata/testdata.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
> fixed-more-info

- testdata/testdata.go
Needed for testing OSD feature
> Added OSD tag to Rule1 and Empty response

- docs/packages/testdata/testdata.html
> Updated doc for testdata

- docs/packages/testdata/testdata.html
- testdata/testdata.go
Added missing docstring.
Fixes #69
N/A
> Fix issue 69

- docs/packages/testdata/testdata.html
- testdata/testdata.go
Added missing docstring
Fixes #70
N/A
> Fix issue 70

- docs/packages/testdata/testdata.html
- testdata/testdata.go
Added missing docstring.
Fixes #75
N/A
> Fix issue 75

- docs/packages/testdata/testdata.html
- testdata/testdata.go
Fix issue #71 - updated docstring
Fixes #71
N/A
> Fix issue #71 - updated docstring

- docs/packages/testdata/testdata.html
> Updated doc

- go.sum
- testdata/testdata.go
New values for new tests
Just let it be
> Added new testdata for new unit tests in related project

- docs/packages/testdata/testdata.html
- testdata/testdata.go
Added missing documentation strings.
Fixes #76
N/A
> Fix issue #76

- CODEOWNERS
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
N/A
> Initial list of code owners

- LICENSE
- README.md
> License badge

- messages/normal/05_rules_hits.clj
- messages/normal/05_rules_hits_org_1.clj
- messages/normal/10_rules_hits.clj
- messages/normal/10_rules_hits_org_1.clj
- messages/normal/15_rules_hits.clj
- messages/normal/15_rules_hits_org_1.clj
- messages/normal/big_results.clj
- messages/normal/big_results_no_skips.clj
- messages/normal/big_results_no_skips_tutorial.clj
- messages/normal/big_results_org_1.clj
- messages/normal/big_results_tutorial.clj
- messages/normal/no_hits.clj
- messages/normal/no_hits_no_skips.clj
- messages/normal/result01.clj
- messages/normal/result02.clj
- messages/normal/result03.clj
- messages/normal/result04.clj
- messages/normal/result05.clj
- messages/normal/tutorial_only.clj
Added version key into messages stored in clj (EDN) format.
- Data update
N/A
> Added version key into messages stored in clj (EDN) format.

- messages/normal_no_version/05_rules_hits.json
- messages/normal_no_version/05_rules_hits_org_1.json
- messages/normal_no_version/10_rules_hits.json
- messages/normal_no_version/10_rules_hits_org_1.json
- messages/normal_no_version/15_rules_hits.json
- messages/normal_no_version/15_rules_hits_org_1.json
- messages/normal_no_version/big_results.json
- messages/normal_no_version/big_results_no_skips.json
- messages/normal_no_version/big_results_no_skips_tutorial.json
- messages/normal_no_version/big_results_org_1.json
- messages/normal_no_version/big_results_tutorial.json
- messages/normal_no_version/no_hits.json
- messages/normal_no_version/no_hits_no_skips.json
- messages/normal_no_version/result01.json
- messages/normal_no_version/result02.json
- messages/normal_no_version/result03.json
- messages/normal_no_version/result04.json
- messages/normal_no_version/result05.json
- messages/normal_no_version/tutorial_only.json
Messages without version
- Data update
N/A
> Messages without version

- messages/normal/05_rules_hits.json
- messages/normal/05_rules_hits_org_1.json
- messages/normal/10_rules_hits.json
- messages/normal/10_rules_hits_org_1.json
- messages/normal/15_rules_hits.json
- messages/normal/15_rules_hits_org_1.json
- messages/normal/big_results.json
- messages/normal/big_results_no_skips.json
- messages/normal/big_results_no_skips_tutorial.json
- messages/normal/big_results_org_1.json
- messages/normal/big_results_tutorial.json
- messages/normal/no_hits.json
- messages/normal/no_hits_no_skips.json
- messages/normal/result01.json
- messages/normal/result02.json
- messages/normal/result03.json
- messages/normal/result04.json
- messages/normal/result05.json
- messages/normal/tutorial_only.json
Fixed issue #96 - correct version field
Fixes #96
- Data update
N/A
> Fixed issue #96 - correct version field

- messages/normal_wrong_version/05_rules_hits.json
- messages/normal_wrong_version/05_rules_hits_org_1.json
- messages/normal_wrong_version/10_rules_hits.json
- messages/normal_wrong_version/10_rules_hits_org_1.json
- messages/normal_wrong_version/15_rules_hits.json
- messages/normal_wrong_version/15_rules_hits_org_1.json
- messages/normal_wrong_version/big_results.json
- messages/normal_wrong_version/big_results_no_skips.json
- messages/normal_wrong_version/big_results_no_skips_tutorial.json
- messages/normal_wrong_version/big_results_org_1.json
- messages/normal_wrong_version/big_results_tutorial.json
- messages/normal_wrong_version/no_hits.json
- messages/normal_wrong_version/no_hits_no_skips.json
- messages/normal_wrong_version/result01.json
- messages/normal_wrong_version/result02.json
- messages/normal_wrong_version/result03.json
- messages/normal_wrong_version/result04.json
- messages/normal_wrong_version/result05.json
- messages/normal_wrong_version/tutorial_only.json
Fixed issue #97 - incorrect version field
Fixes #97
- Data update
N/A
> Fixed issue #97 - incorrect version field

- messages/invalid_no_report/05_rules_hits.clj
- messages/invalid_no_report/05_rules_hits_org_1.clj
- messages/invalid_no_report/10_rules_hits.clj
- messages/invalid_no_report/10_rules_hits_org_1.clj
- messages/invalid_no_report/15_rules_hits.clj
- messages/invalid_no_report/15_rules_hits_org_1.clj
- messages/invalid_no_report/big_results.clj
- messages/invalid_no_report/big_results_no_skips.clj
- messages/invalid_no_report/big_results_no_skips_tutorial.clj
- messages/invalid_no_report/big_results_org_1.clj
- messages/invalid_no_report/big_results_tutorial.clj
- messages/invalid_no_report/no_hits.clj
- messages/invalid_no_report/no_hits_no_skips.clj
- messages/invalid_no_report/result01.clj
- messages/invalid_no_report/result02.clj
- messages/invalid_no_report/result03.clj
- messages/invalid_no_report/result04.clj
- messages/invalid_no_report/result05.clj
- messages/invalid_no_report/tutorial_only.clj
Invalid messages - no `report` attribute
N/A
> Invalid messages - no `report` attribute

- messages/invalid_wrong_report/05_rules_hits.clj
- messages/invalid_wrong_report/05_rules_hits_org_1.clj
- messages/invalid_wrong_report/10_rules_hits.clj
- messages/invalid_wrong_report/10_rules_hits_org_1.clj
- messages/invalid_wrong_report/15_rules_hits.clj
- messages/invalid_wrong_report/15_rules_hits_org_1.clj
- messages/invalid_wrong_report/big_results.clj
- messages/invalid_wrong_report/big_results_no_skips.clj
- messages/invalid_wrong_report/big_results_no_skips_tutorial.clj
- messages/invalid_wrong_report/big_results_org_1.clj
- messages/invalid_wrong_report/big_results_tutorial.clj
- messages/invalid_wrong_report/no_hits.clj
- messages/invalid_wrong_report/no_hits_no_skips.clj
- messages/invalid_wrong_report/result01.clj
- messages/invalid_wrong_report/result02.clj
- messages/invalid_wrong_report/result03.clj
- messages/invalid_wrong_report/result04.clj
- messages/invalid_wrong_report/result05.clj
- messages/invalid_wrong_report/tutorial_only.clj
Messages with wrong report
N/A
> Messages with wrong report

- go.mod
Bump-up Insights operator utils library version to 1.8.2
Fixes #106
N/A
> Bump-up Insights operator utils library version to 1.8.2

- messages/normal/05_rules_hits.json
- messages/normal/05_rules_hits_org_1.json
- messages/normal/10_rules_hits.json
- messages/normal/10_rules_hits_org_1.json
- messages/normal/15_rules_hits.json
- messages/normal/15_rules_hits_org_1.json
- messages/normal/big_results.json
- messages/normal/big_results_no_skips.json
- messages/normal/big_results_no_skips_tutorial.json
- messages/normal/big_results_org_1.json
- messages/normal/big_results_tutorial.json
- messages/normal/no_hits.json
- messages/normal/no_hits_no_skips.json
- messages/normal/result01.json
- messages/normal/result02.json
- messages/normal/result03.json
- messages/normal/result04.json
- messages/normal/result05.json
- messages/normal/tutorial_only.json
Messages with account number
N/A
> Messages with account number

- messages/normal/05_rules_hits.clj
- messages/normal/05_rules_hits_org_1.clj
- messages/normal/10_rules_hits.clj
- messages/normal/10_rules_hits_org_1.clj
- messages/normal/15_rules_hits.clj
- messages/normal/15_rules_hits_org_1.clj
- messages/normal/big_results.clj
- messages/normal/big_results_no_skips.clj
- messages/normal/big_results_no_skips_tutorial.clj
- messages/normal/big_results_org_1.clj
- messages/normal/big_results_tutorial.clj
- messages/normal/no_hits.clj
- messages/normal/no_hits_no_skips.clj
- messages/normal/result01.clj
- messages/normal/result02.clj
- messages/normal/result03.clj
- messages/normal/result04.clj
- messages/normal/result05.clj
- messages/normal/tutorial_only.clj
Account number normal messages in EDN format
N/A
> Account number normal messages in EDN format

- messages/normal/05_rules_hits.json
- messages/normal/05_rules_hits_org_1.json
- messages/normal/10_rules_hits.json
- messages/normal/10_rules_hits_org_1.json
- messages/normal/15_rules_hits.json
- messages/normal/15_rules_hits_org_1.json
- messages/normal/big_results.json
- messages/normal/big_results_no_skips.json
- messages/normal/big_results_no_skips_tutorial.json
- messages/normal/big_results_org_1.json
- messages/normal/big_results_tutorial.json
- messages/normal/no_hits.json
- messages/normal/no_hits_no_skips.json
- messages/normal/result01.json
- messages/normal/result02.json
- messages/normal/result03.json
- messages/normal/result04.json
- messages/normal/result05.json
- messages/normal/tutorial_only.json
Normal messages with account number new schema version
N/A
> Normal messages with account number new schema version

- messages/invalid_no_account_number/05_rules_hits.json
- messages/invalid_no_account_number/05_rules_hits_org_1.json
- messages/invalid_no_account_number/10_rules_hits.json
- messages/invalid_no_account_number/10_rules_hits_org_1.json
- messages/invalid_no_account_number/15_rules_hits.json
- messages/invalid_no_account_number/15_rules_hits_org_1.json
- messages/invalid_no_account_number/big_results.json
- messages/invalid_no_account_number/big_results_no_skips.json
- messages/invalid_no_account_number/big_results_no_skips_tutorial.json
- messages/invalid_no_account_number/big_results_org_1.json
- messages/invalid_no_account_number/big_results_tutorial.json
- messages/invalid_no_account_number/no_hits.json
- messages/invalid_no_account_number/no_hits_no_skips.json
- messages/invalid_no_account_number/result01.json
- messages/invalid_no_account_number/result02.json
- messages/invalid_no_account_number/result03.json
- messages/invalid_no_account_number/result04.json
- messages/invalid_no_account_number/result05.json
- messages/invalid_no_account_number/tutorial_only.json
Normal messages without account numbers
N/A
> Normal messages without account numbers

- messages/normal_for_notification_tests/03_rules_hits_org_1.json
- messages/normal_for_notification_tests/03_rules_hits_org_2.json
- messages/normal_for_notification_tests/04_rules_hits_org_1.json
- messages/normal_for_notification_tests/04_rules_hits_org_2.json
- messages/normal_for_notification_tests/05_rules_hits_org_1.json
- messages/normal_for_notification_tests/05_rules_hits_org_3.json
- messages/normal_for_notification_tests/no_hits_org_1.json
- messages/normal_for_notification_tests/produce.sh
Messages for notification tests
N/A
> Messages for notification tests

- messages/invalid_no_cluster_name/05_rules_hits.json
- messages/invalid_no_cluster_name/05_rules_hits_org_1.json
- messages/invalid_no_cluster_name/10_rules_hits.json
- messages/invalid_no_cluster_name/10_rules_hits_org_1.json
- messages/invalid_no_cluster_name/15_rules_hits.json
- messages/invalid_no_cluster_name/15_rules_hits_org_1.json
- messages/invalid_no_cluster_name/big_results.json
- messages/invalid_no_cluster_name/big_results_no_skips.json
- messages/invalid_no_cluster_name/big_results_no_skips_tutorial.json
- messages/invalid_no_cluster_name/big_results_org_1.json
- messages/invalid_no_cluster_name/big_results_tutorial.json
- messages/invalid_no_cluster_name/no_hits.json
- messages/invalid_no_cluster_name/no_hits_no_skips.json
- messages/invalid_no_cluster_name/result01.json
- messages/invalid_no_cluster_name/result02.json
- messages/invalid_no_cluster_name/result03.json
- messages/invalid_no_cluster_name/result04.json
- messages/invalid_no_cluster_name/result05.json
- messages/invalid_no_cluster_name/tutorial_only.json
Messages with no cluster name in order to test the whole external data pipeline
Fixes #108
N/A
> Messages with no cluster name in order to test the whole external data pipeline

- messages/invalid_no_report/05_rules_hits.json
- messages/invalid_no_report/05_rules_hits_org_1.json
- messages/invalid_no_report/10_rules_hits.json
- messages/invalid_no_report/10_rules_hits_org_1.json
- messages/invalid_no_report/15_rules_hits.json
- messages/invalid_no_report/15_rules_hits_org_1.json
- messages/invalid_no_report/big_results.json
- messages/invalid_no_report/big_results_no_skips.json
- messages/invalid_no_report/big_results_no_skips_tutorial.json
- messages/invalid_no_report/big_results_org_1.json
- messages/invalid_no_report/big_results_tutorial.json
- messages/invalid_no_report/no_hits.json
- messages/invalid_no_report/no_hits_no_skips.json
- messages/invalid_no_report/result01.json
- messages/invalid_no_report/result02.json
- messages/invalid_no_report/result03.json
- messages/invalid_no_report/result04.json
- messages/invalid_no_report/result05.json
- messages/invalid_no_report/tutorial_only.json
Fixed issue #109
Fixes #109
N/A
> Fixed issue #109

- messages/invalid_no_last_checked/05_rules_hits.json
- messages/invalid_no_last_checked/05_rules_hits_org_1.json
- messages/invalid_no_last_checked/10_rules_hits.json
- messages/invalid_no_last_checked/10_rules_hits_org_1.json
- messages/invalid_no_last_checked/15_rules_hits.json
- messages/invalid_no_last_checked/15_rules_hits_org_1.json
- messages/invalid_no_last_checked/big_results.json
- messages/invalid_no_last_checked/big_results_no_skips.json
- messages/invalid_no_last_checked/big_results_no_skips_tutorial.json
- messages/invalid_no_last_checked/big_results_org_1.json
- messages/invalid_no_last_checked/big_results_tutorial.json
- messages/invalid_no_last_checked/no_hits.json
- messages/invalid_no_last_checked/no_hits_no_skips.json
- messages/invalid_no_last_checked/result01.json
- messages/invalid_no_last_checked/result02.json
- messages/invalid_no_last_checked/result03.json
- messages/invalid_no_last_checked/result04.json
- messages/invalid_no_last_checked/result05.json
- messages/invalid_no_last_checked/tutorial_only.json
Fixed issue #110
Fixes #110
N/A
> Fixed issue #110

- messages/invalid_no_version/05_rules_hits.json
- messages/invalid_no_version/05_rules_hits_org_1.json
- messages/invalid_no_version/10_rules_hits.json
- messages/invalid_no_version/10_rules_hits_org_1.json
- messages/invalid_no_version/15_rules_hits.json
- messages/invalid_no_version/15_rules_hits_org_1.json
- messages/invalid_no_version/big_results.json
- messages/invalid_no_version/big_results_no_skips.json
- messages/invalid_no_version/big_results_no_skips_tutorial.json
- messages/invalid_no_version/big_results_org_1.json
- messages/invalid_no_version/big_results_tutorial.json
- messages/invalid_no_version/no_hits.json
- messages/invalid_no_version/no_hits_no_skips.json
- messages/invalid_no_version/result01.json
- messages/invalid_no_version/result02.json
- messages/invalid_no_version/result03.json
- messages/invalid_no_version/result04.json
- messages/invalid_no_version/result05.json
- messages/invalid_no_version/tutorial_only.json
Fixed issue #111
Fixes #111
N/A
> Fixed issue #111

- messages/invalid_no_organization_id/05_rules_hits.json
- messages/invalid_no_organization_id/05_rules_hits_org_1.json
- messages/invalid_no_organization_id/10_rules_hits.json
- messages/invalid_no_organization_id/10_rules_hits_org_1.json
- messages/invalid_no_organization_id/15_rules_hits.json
- messages/invalid_no_organization_id/15_rules_hits_org_1.json
- messages/invalid_no_organization_id/big_results.json
- messages/invalid_no_organization_id/big_results_no_skips.json
- messages/invalid_no_organization_id/big_results_no_skips_tutorial.json
- messages/invalid_no_organization_id/big_results_org_1.json
- messages/invalid_no_organization_id/big_results_tutorial.json
- messages/invalid_no_organization_id/no_hits.json
- messages/invalid_no_organization_id/no_hits_no_skips.json
- messages/invalid_no_organization_id/result01.json
- messages/invalid_no_organization_id/result02.json
- messages/invalid_no_organization_id/result03.json
- messages/invalid_no_organization_id/result04.json
- messages/invalid_no_organization_id/result05.json
- messages/invalid_no_organization_id/tutorial_only.json
> Fix issue #117

- messages/invalid_wrong_cluster_name/05_rules_hits.json
- messages/invalid_wrong_cluster_name/05_rules_hits_org_1.json
- messages/invalid_wrong_cluster_name/10_rules_hits.json
- messages/invalid_wrong_cluster_name/10_rules_hits_org_1.json
- messages/invalid_wrong_cluster_name/15_rules_hits.json
- messages/invalid_wrong_cluster_name/15_rules_hits_org_1.json
- messages/invalid_wrong_cluster_name/big_results.json
- messages/invalid_wrong_cluster_name/big_results_no_skips.json
- messages/invalid_wrong_cluster_name/big_results_no_skips_tutorial.json
- messages/invalid_wrong_cluster_name/big_results_org_1.json
- messages/invalid_wrong_cluster_name/big_results_tutorial.json
- messages/invalid_wrong_cluster_name/no_hits.json
- messages/invalid_wrong_cluster_name/no_hits_no_skips.json
- messages/invalid_wrong_cluster_name/result01.json
- messages/invalid_wrong_cluster_name/result02.json
- messages/invalid_wrong_cluster_name/result03.json
- messages/invalid_wrong_cluster_name/result04.json
- messages/invalid_wrong_cluster_name/result05.json
- messages/invalid_wrong_cluster_name/tutorial_only.json
Messages with wrong `cluster_name` attribute in order to be able to test external data pipeline
Fixes #115
N/A
> Messages with wrong cluster_name attribute in order to be able to test external data pipeline

- messages/invalid_wrong_last_checked/05_rules_hits.json
- messages/invalid_wrong_last_checked/05_rules_hits_org_1.json
- messages/invalid_wrong_last_checked/10_rules_hits.json
- messages/invalid_wrong_last_checked/10_rules_hits_org_1.json
- messages/invalid_wrong_last_checked/15_rules_hits.json
- messages/invalid_wrong_last_checked/15_rules_hits_org_1.json
- messages/invalid_wrong_last_checked/big_results.json
- messages/invalid_wrong_last_checked/big_results_no_skips.json
- messages/invalid_wrong_last_checked/big_results_no_skips_tutorial.json
- messages/invalid_wrong_last_checked/big_results_org_1.json
- messages/invalid_wrong_last_checked/big_results_tutorial.json
- messages/invalid_wrong_last_checked/no_hits.json
- messages/invalid_wrong_last_checked/no_hits_no_skips.json
- messages/invalid_wrong_last_checked/result01.json
- messages/invalid_wrong_last_checked/result02.json
- messages/invalid_wrong_last_checked/result03.json
- messages/invalid_wrong_last_checked/result04.json
- messages/invalid_wrong_last_checked/result05.json
- messages/invalid_wrong_last_checked/tutorial_only.json
Messages with wrong `last_checked` attribute in order to be able to test external data pipeline
Fixes #113
N/A
> Messages with wrong last_checked attribute in order to be able to test external data pipeline

- testdata/testdata.go
Condition field has been removed from provided rules. This PR updates the related testing data used by the other services.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
CI of other services
> Remove condition field from error key structure

- .travis.yml
> CI job definition

- README.md
- messages/broken/README.md
- messages/normal/README.md
- messages/normal_for_notification_tests/README.md
- messages/normal_no_version/README.md
- messages/normal_wrong_version/README.md
Documentation normal messages
N/A
> Documentation normal messages

- README.md
Mention CCX Notification Writer
N/A
> Mention CCX Notification Writer

- README.md
Invalid messages description
N/A
> Invalid messages description

- go.mod
- go.sum
- testdata/testdata.go
Blocked by:
https://github.com/RedHatInsights/insights-operator-utils/pull/179
Needed for:
https://github.com/RedHatInsights/insights-results-smart-proxy/pull/602
Updates test data used in smart-proxy tests.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
tested alongside smart-proxy locally
> update testdata for new content structs

- testdata/testdata.go
changed impact type from string to int
Fixes CCXDEV-5613
> updated impact type

- go.mod
- go.sum
- testdata/testdata.go
add composite rule IDs to be used in tests in aggregator and smart-proxy
locally with aggregator tests
> add composite rule IDs to be used in tests

- go.mod
- go.sum
- testdata/testdata.go
Added a new rule to be used in https://github.com/RedHatInsights/insights-results-smart-proxy/pull/724.
`make before_commit` passes.
> [CCXDEV-6254] Add RuleContent1V2 to be used in smart-proxy

- PULL_REQUEST_TEMPLATE.md
Updated pull request template.
Fixes #159
N/A
> Fixed issue #159

- testdata/gwt_tokens.go
GWT tokens to be used in tests
N/A
> GWT tokens to be used in tests

- testdata/testdata.go
Add test data for smart-proxy and insights-results-aggregator UTs related with system-wide rules enabling/disabling.
Used module in corresponding repositories
> Add test data for organisation-wide disabled rules

- go.mod
- testdata/testdata.go
Update testdata to include the gathered at for reports used in tests.
- Refactor (refactoring code, removing useless files)
> Update test data to include gathered_at

- storage/cluster_rule_toggle.sql
Cluster rule toggle data for testing
N/A
> Cluster rule toggle data

- testdata/testdata.go
Add a ClusterVersion to use in the unit tests of CCXDEV-6971 in the aggregator.
Part of #CCXDEV-6971
> [CCXDEV-6971] Add ClusterVersion

- .travis.yml
- gosec.sh
- testdata/gwt_tokens.go
Gosec script to be run on CI
Done on CI
> Gosec script to be run on CI

- testdata/testdata.go
re-adding functions removed in https://github.com/RedHatInsights/insights-results-aggregator-data/pull/211/files because I cannot find them anywhere.
Fixes # (issue)
n/a
> re-add missing functions

- messages/broken/without_attribute_OrgID_Report.clj
- messages/broken/without_attribute_Report.clj
More broken messages
- Test messages
N/A
> More broken messages

- messages/invalid_wrong_report/05_rules_hits.clj
- messages/invalid_wrong_report/05_rules_hits_org_1.clj
- messages/invalid_wrong_report/10_rules_hits.clj
- messages/invalid_wrong_report/10_rules_hits_org_1.clj
- messages/invalid_wrong_report/15_rules_hits.clj
- messages/invalid_wrong_report/15_rules_hits_org_1.clj
- messages/invalid_wrong_report/big_results.clj
- messages/invalid_wrong_report/big_results_no_skips.clj
- messages/invalid_wrong_report/big_results_no_skips_tutorial.clj
- messages/invalid_wrong_report/big_results_org_1.clj
- messages/invalid_wrong_report/big_results_tutorial.clj
- messages/invalid_wrong_report/no_hits.clj
- messages/invalid_wrong_report/no_hits_no_skips.clj
- messages/invalid_wrong_report/result01.clj
- messages/invalid_wrong_report/result02.clj
- messages/invalid_wrong_report/result03.clj
- messages/invalid_wrong_report/result04.clj
- messages/invalid_wrong_report/result05.clj
- messages/invalid_wrong_report/tutorial_only.clj
Reformatted messages with wrong report
=Reformat 
N/A
> Reformatted messages with wrong report
